name: .NET Core XUnit Tests
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restore Dependencies
      run: dotnet restore Zenflow.Tests 

    - name: Build Solution
      run: dotnet build Zenflow.Tests --configuration Release --no-restore

    - name: Run XUnit Tests
      run: dotnet test Zenflow.Tests --configuration Release --no-build --verbosity normal
